[FIX] mail: prevent error when sending sms
This error occurs when the user attempts to send a message using the
'Mitchell Admin' mobile number after creating a new 'Website Live Chat Channels'.

Steps to reproduce:
- Install the 'im_livechat' module
- Create new 'Website Live Chat Channels' > Click on 'Mitchell Admin'
- Add mobile number > Click on the 'SMS' smart button on the right side of the
  mobile field
- Add mobile number in 'Recipient' and add a message in 'Message' > 'Send SMS'

Traceback : AttributeError
'bool' object has no attribute 'split'

At [1], we are encountering an error because 'sanitized_numbers' is returning
'False'. This issue occurs only when sending an SMS message from 'res.users'
since we do not retrieve any partner records from it. As a result, there is no
number available in the composer at [2], causing 'sanitized_numbers' to be
False. This happens because 'res.users' is not an instance of
'self.pool['mail.thread']'.

This commit will resolve the above error by inherting 'mail.thread' in 'res.users'.

[1]- https://github.com/odoo/odoo/blob/095819c76361880e106aaa9e4ac9eca84fddab02/addons/sms/wizard/sms_composer.py#L207

[2]- https://github.com/odoo/odoo/blob/b6c82de598f512750ddf80c7b4aade96346207e5/addons/sms/wizard/sms_composer.py#L155

sentry-468153551