[FIX] sale_stock: skip logging downpayment line changes
Versions
--------
- 17.4+

Steps
-----
1. Configure UoM decimal accuracy to be 0 digits;
2. create, confirm a SO;
3. create a downpayment invoice;
4. go back to the SO;
5. modify the product line's price.

Issue
-----
> AssertionError: precision_rounding must be positive, got 0.

Cause
-----
When checking for quantity changes to log on `write`, a fallback
rounding value is retrieved using `precision_get`. This returns a
`precision_digits` value, but is being used as a `precision_rounding`
value, resulting in an error when it is 0.

In previous versions, this fallback value was never used, as
`display_type` lines were skipped, and any other line is guaranteed to
have a `product_uom.rounding` value.

As of 9aa52dd6418e, the constraint was changed for `is_downpayment`
lines not having to be of `display_type` nor require a `product_uom`
value, meaning the faulty fallback value now gets used.

Solution
--------
Remove the fallback value, and only log lines with a `product_uom`
value.

opw-4566621

closes odoo/odoo#210663

X-original-commit: acc41aea68642222dbd5df030e353bf8f27be951
Signed-off-by: Steve Van Essche <svs@odoo.com>
Signed-off-by: Levi Siuzdak <sile@odoo.com>