[FIX] account: Fix multi company issue
If there are multi company in database and
there is menu which open 'account.payament.method.line'
records with display it throw error mutli company error.
during computing dispay_name because on journal there is
check company. To fixing this made new access rule.

```
  File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 5779, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3744, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 6680, in __getitem__
    return self._fields[key].__get__(self)
   File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1742, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1908, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 4949, in _compute_field_value
    determine(field.compute, self)
   File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 81, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/19.0/addons/account/models/account_payment_method.py", line 137, in _compute_display_name
    method.display_name = f"{method.name} ({method.journal_id.name})"
   File "/home/odoo/src/odoo/19.0/odoo/orm/fields.py", line 1700, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3769, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/19.0/odoo/orm/models.py", line 3815, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: ¡Uy! Parece que ha tropezado con unos registros ultrasecretos.

Lo sentimos, Administrator (id=2) no tiene permiso de acceso 'leer' a:
- Diario (account.journal)

Si realmente necesita acceso, quizá pueda ganarse a su amable administrador con un lote de galletas recién horneadas.

Este es un problema de varias compañías, quizá pueda acceder al registro si cambia a la compañía: GRUES I SERVEIS D’ELEVACIÓ, S.L..
```
opw-5406806
upg-3525447