[FIX] stock_account: prevent ZeroDivisionError in _run_avco
Traceback :
  ```File /home/odoo/src/odoo/19.0/addons/stock_account/models/product.py,
line 273, in _run_avco
    in_value = in_value * lot_qty / in_qty
 ZeroDivisionError: float division by zero```

During inventory valuation for products using AVCO and lot tracking,
a ZeroDivisionError occurs if 'in_qty' is zero.

This situation occured because customer had move line with 0 in quantity
that caused error here
https://github.com/odoo/odoo/blob/19.0/addons/stock_account/models/product.py#L273
and above traceback occured

This commit adds a safety check to ensure the division only occurs
if 'in_qty' is non-zero