[FIX] web_editor: fix traceback when user upload having no name
Currently, a traceback may arise when the user uploads a file with no name.

Error:-
"TypeError: Web_Editor.add_data() missing 1 required positional argument: 'name'"

When the value of the name we get from the RPC call is undefined, we get this
traceback on the backend.

If there is no `name`, this case is already  handled in the py side
https://github.com/odoo/odoo/blob/6838782baf222db4591edce5fe80f5af3a39810c/addons/web_editor/controllers/main.py#L261-L266

So by just giving the fallback value if there is no name we can resolve this issue.

sentry-5741581459