Cherry pick of c71a7c62eb5bbd7130a34d539bb7ecebd1a5b775 failed
stdout:
CONFLICT (modify/delete): addons/l10n_ec/data/account.account.template.csv deleted in HEAD and modified in c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry).  Version c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry) of addons/l10n_ec/data/account.account.template.csv left in tree.
CONFLICT (modify/delete): addons/l10n_ec/data/account_group_template_data.xml deleted in HEAD and modified in c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry).  Version c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry) of addons/l10n_ec/data/account_group_template_data.xml left in tree.
CONFLICT (modify/delete): addons/l10n_ec/data/account_tax_group_data.xml deleted in HEAD and modified in c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry).  Version c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry) of addons/l10n_ec/data/account_tax_group_data.xml left in tree.
CONFLICT (modify/delete): addons/l10n_ec/i18n/es_EC.po deleted in HEAD and modified in c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry).  Version c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry) of addons/l10n_ec/i18n/es_EC.po left in tree.
CONFLICT (modify/delete): addons/l10n_ec/models/account_chart_template.py deleted in HEAD and modified in c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry).  Version c71a7c62eb5 ([IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry) of addons/l10n_ec/models/account_chart_template.py left in tree.

stderr:
20:23:25.779952 git.c:455               trace: built-in: git cherry-pick c71a7c62eb5bbd7130a34d539bb7ecebd1a5b775
error: could not apply c71a7c62eb5... [IMP] l10n_ec: Add and fix tax group accounts to automate tax closing entry
hint: After resolving the conflicts, mark them with
hint: "git add/rm <pathspec>", then run
hint: "git cherry-pick --continue".
hint: You can instead skip this commit with "git cherry-pick --skip".
hint: To abort and get back to the state before "git cherry-pick",
hint: run "git cherry-pick --abort".
----------
status: