[FIX] account: skip earnings check during chart template load
Steps to reproduce:
- Have an existing Odoo 17.0 database with a company whose country is set to
  Oman (or any country whose localization module did not exist in 17.0).
- Confirm the company has no chart template installed
  (company.chart_template is False).
- Upgrade the database to 18.0, where l10n_om is introduced for the first
  time.

see https://github.com/odoo/odoo/pull/201016

Before this commit, the upgrade crashes with:
  ```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1414, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 116, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 621, in load_modules
    model._register_hook()
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_module.py", line 102, in _register_hook
    self.env.registry._auto_install_template(self.env)
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_module.py", line 78, in try_loading
    env['account.chart.template'].try_loading(
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 163, in try_loading
    return self._load(template_code, company, install_demo, force_create)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 230, in _load
    self._load_data(data)
  File "/tmp/tmpblvsx160/migrations/account/0.0.0/pre-ensure-deferred-accounts.py", line 37, in _load_data
    return super()._load_data(data, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 676, in _load_data
    created_records[model] = self.with_context(lang='en_US').env[model]._load_records(all_records_vals, ignore_duplicates=ignore_duplicates)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5531, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5435, in _load_records_create
    records = self.create(vals_list)
  File "<decorator-gen-228>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/addons/account/models/account_account.py", line 992, in create
    )).create(vals_list_for_company)
  File "<decorator-gen-142>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 290, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-122>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpblvsx160/migrations/util/orm.py", line 267, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpblvsx160/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-31>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 498, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5039, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5297, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1636, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/account/models/account_account.py", line 346, in _check_account_is_bank_journal_bank_account
    self.env['account.account'].flush_model(['account_type'])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 6773, in flush_model
    self._recompute_model(fnames)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7337, in _recompute_model
    self._recompute_field(field)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7365, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1469, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1442, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1491, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 443, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5307, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1636, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/account/models/account_account.py", line 42, in _check_account_type_unique_current_year_earning
    raise ValidationError(_('You cannot have more than one account with "Current Year Earnings" as type. (accounts: %s)', [a.code for a in account_unaffected_earnings]))
odoo.exceptions.ValidationError: You cannot have more than one account with "Current Year Earnings" as type. (accounts: ['999999', False])
```

When a localization module is auto-installed via _register_hook on a
company that has no chart_template yet, _load's reload_template is False,
so _pre_reload_data() is never called and the generic equity_unaffected
https://github.com/odoo/odoo/blob/18.0/addons/account/models/chart_template.py#L203-L228
account (999999) created before the localization existed is never cleaned
https://github.com/odoo/odoo/blob/18.0/addons/account/models/chart_template.py#L336
https://github.com/odoo/odoo/pull/201016/changes#diff-77c111e3485fd8ecbdf3add38cd79d4c54bbb69285136e369c65be4faa26c356R75
up. When the new localization then creates its own current_year_earnings
account, _check_account_type_unique_current_year_earning finds two
equity_unaffected accounts for the company and raises.
https://github.com/odoo/odoo/blob/18.0/addons/account/models/account_account.py#L33-L42

This commit skips the check while chart_template_load is set in the
context, consistent with the other invariants already relaxed during an
in-progress template load (tracking_disable, delay_account_group_sync).
The transient duplicate is expected and gets resolved once the load
completes.
https://github.com/odoo/odoo/commit/41b86c40a74b082d23d2ed0f091d1f2001702d08

opw-6476132
upg-4584954