[FIX] attachment_indexation: prevent ModuleNotFoundError for pdfminer
Traceback :
```
  File /home/odoo/src/odoo/19.0/addons/attachment_indexation/models/ir_attachment.py, line 18, in <module>
    if not importlib.util.find_spec('pdfminer.high_level') or not importlib.util.find_spec('pdfminer'):
  File /usr/lib/python3.10/importlib/util.py, line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'pdfminer'
```

Earlier it only checked if pdfminer is installed or not ,but now it checks
pdfminer.high_level and if pdfminer is not there it will cause above traceback .
So after this change it will first check pfdminer and then pdfminer.high_level.