[FIX] account: fix IndexError for archived company during migration
When migrating from 16.0 to 17.0, an IndexError can occur in
`account.chart.template.[ref](https://github.com/odoo/odoo/blob/17.0/addons/account/models/chart_template.py#L1077-L1083)`
method call when creating the fiscal position for the archived company.

**Traceback:**
```
  File "/home/odoo/odoo18/enterprise/l10n_mx_edi/models/account_move.py", line 643, in _compute_l10n_mx_edi_cfdi_to_public
    self.env['l10n_mx_edi.document']._add_customer_cfdi_values(
  File "/home/odoo/odoo18/enterprise/l10n_mx_edi/models/l10n_mx_edi_document.py", line 678, in _add_customer_cfdi_values
    export_fiscal_position = company._l10n_mx_edi_get_foreign_customer_fiscal_position()
  File "/home/odoo/odoo18/enterprise/l10n_mx_edi/models/res_company.py", line 74, in _l10n_mx_edi_get_foreign_customer_fiscal_position
    fiscal_position = self.env['account.chart.template'].with_company(self).ref('account_fiscal_position_foreign', raise_if_not_found=False)
  File "/home/odoo/odoo18/community/addons/account/models/chart_template.py", line 1082, in ref
    or self.env.ref(f"account.{self.env.company.parent_ids[0].id}_{xmlid}", raise_if_not_found)
  File "/home/odoo/odoo18/community/odoo/models.py", line 6697, in __getitem__
    return self.browse((self._ids[key],))
IndexError: tuple index out of range
```
**Root Cause:**
- There is no fiscal position present for a company_id of 7 (archived)
in the customer database. So during the migration trying to create
the fiscal position for that company.
Then an IndexError occurs because
it gets [parent_ids](https://github.com/odoo/odoo/blob/17.0/addons/account/models/chart_template.py#L1082) empty record set for the archived company.
The context is lost, so parent_ids is computed without active_test=False,
so non-active records are excluded.

**Fix:**
Explicitly evaluate `parent_ids` with `active_test=False` to
include inactive companies:

    ```self.env.company.with_context(active_test=False).parent_ids[0]```

This ensures migration continues even when the company is archived, while keeping behavior unchanged for active companies.

**Steps to reproduce:**
1. Just fresh database for version 16.0
2. Install the l10n_mx
3. Just delete the ir_model_data for model `account.fiscal.position` for company 3
4. Then archived that company
5. Migrate to 17.0 and IndexError occurs.

OPW: 4977543
UPG: 3047262