[FIX] analytic: handle missing FK constraints in migration
Some customer databases no longer have the expected foreign key constraints on
account_analytic_line (for example, account_analytic_line_x_plan2019_id_fkey)
due to prior schema inconsistencies.

While the ORM safely handles the possibility of a missing field definition, the
migration script unconditionally attempted to drop the foreign key constraint,
even when the corresponding column or constraint no longer existed.
This led to the following error during migration:

In principle, each analytic plan in account_analytic_plan should have a
corresponding field (x_plan<ID>_id) in account_analytic_line.
However, due to prior schema divergences, this assumption may not always hold.

This commit introduces a safeguard to verify that both the column and its
constraint exist before attempting to drop them.
If present, the constraint is replaced with a new one using ON DELETE RESTRICT.
This ensures the migration remains safe, robust, and idempotent across all
databases.

```
2025-11-10 05:57:39,573 27 ERROR db_3271330 odoo.sql_db: bad query: b'ALTER TABLE "account_analytic_line" DROP CONSTRAINT "account_analytic_line_x_plan2019_id_fkey"'
ERROR: constraint "account_analytic_line_x_plan2019_id_fkey" of relation "account_analytic_line" does not exist

2025-11-10 05:57:39,577 27 WARNING db_3271330 odoo.modules.loading: Transient module states were reset
2025-11-10 05:57:39,577 27 ERROR db_3271330 odoo.registry: Failed to load registry
2025-11-10 05:57:39,577 27 CRITICAL db_3271330 odoo.service.server: Failed to initialize database `db_3271330`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/19.0/odoo/service/server.py", line 1514, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'], reinit_modules=config['reinit'])
  File "/home/odoo/src/odoo/19.0/odoo/tools/func.py", line 88, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/19.0/odoo/orm/registry.py", line 185, in new
    load_modules(
  File "/home/odoo/src/odoo/19.0/odoo/modules/loading.py", line 449, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/19.0/odoo/modules/loading.py", line 165, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/19.0/odoo/modules/migration.py", line 220, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/19.0/odoo/modules/migration.py", line 257, in exec_script
    mod.migrate(cr, installed_version)
  File "/home/odoo/src/odoo/19.0/addons/analytic/migrations/1.2/pre-migrate.py", line 30, in migrate
    sql.drop_constraint(cr, 'account_analytic_line', f'account_analytic_line_{column}_fkey')
  File "/home/odoo/src/odoo/19.0/odoo/tools/sql.py", line 466, in drop_constraint
    cr.execute(SQL(
  File "/home/odoo/src/odoo/19.0/odoo/sql_db.py", line 426, in execute
    self._obj.execute(query, params)
psycopg2.errors.UndefinedObject: constraint "account_analytic_line_x_plan2019_id_fkey" of relation "account_analytic_line" does not exist

 SELECT 1 FROM information_schema.columns
             WHERE table_name='account_analytic_line' AND column_name='x_plan2019_id';
+----------+
| ?column? |
|----------|
+----------+
SELECT 0
Time: 0.043s

 select * from ir_model_fields where name='x_plan2019_id';
-[ RECORD 1 ]-------------------------
id                       | 35562
relation_field_id        | <null>
model_id                 | 367
related_field_id         | <null>
size                     | <null>
create_uid               | <null>
write_uid                | <null>
name                     | x_plan2019_id
complete_name            | <null>
model                    | project.project
relation                 | account.analytic.account
relation_field           | <null>
ttype                    | many2one
related                  | <null>
state                    | manual
on_delete                | set null
domain                   | <null>
relation_table           | <null>
column1                  | <null>
column2                  | <null>
depends                  | <null>
field_description        | {"en_US": "Project", "hr_HR": "Projekti", "sl_SI": "Projekti"}
help                     | <null>
compute                  | <null>
copied                   | False
required                 | False
readonly                 | False
index                    | False
translate                | False
group_expand             | <null>
selectable               | True
store                    | True
create_date              | <null>
write_date               | <null>
tracking                 | <null>
website_form_blacklisted | True
currency_field           | <null>
sanitize                 | <null>
sanitize_overridable     | <null>
sanitize_tags            | <null>
sanitize_attributes      | <null>
sanitize_style           | <null>
sanitize_form            | <null>
strip_style              | <null>
strip_classes            | <null>
company_dependent        | False
SELECT 1
Time: 0.008s

select id,name,noupdate,model,module,res_id from ir_model_data where res_id=35562 and model='ir.model.fields';
+--------+--------------------------------------+----------+-----------------+---------+--------+
| id     | name                                 | noupdate | model           | module  | res_id |
|--------+--------------------------------------+----------+-----------------+---------+--------|
| 244490 | field_project_project__x_plan2019_id | False    | ir.model.fields | project | 35562  |
+--------+--------------------------------------+----------+-----------------+---------+--------+
SELECT 1
Time: 0.018s
```

opw-5252496
upg-3271330
tbg-2267