[FIX] repair: handle archived production locations
Warehouses require at least one Production location to avoid triggering
errors, but archived Production locations are not considered missing.

The logic is borrowed from the `mrp` module and has been aligned to handle
this case correctly by including inactive Production locations in the
lookup.

This issue was encountered during upgrades.

Steps to reproduce:
- In 17.0, install the `repair` module without installing `mrp`
- Archive the Production locations
- Upgrade to 18.0
- An error is raised during the stock upgrade

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1366, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 129, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 523, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 222, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 259, in exec_script
    mod.migrate(cr, installed_version)
  File "/tmp/tmpjen4whht/migrations/stock/saas~17.3.1.1/end-migrate.py", line 16, in migrate
    new_types_vals = warehouse._create_or_update_sequences_and_picking_types()
  File "/home/odoo/src/odoo/18.0/addons/stock/models/stock_warehouse.py", line 374, in _create_or_update_sequences_and_picking_types
    create_data, max_sequence = self._get_picking_type_create_values(max_sequence)
  File "/home/odoo/src/odoo/18.0/addons/repair/models/stock_warehouse.py", line 29, in _get_picking_type_create_values
    prod_location = self._get_production_location()
  File "/home/odoo/src/odoo/18.0/addons/repair/models/stock_warehouse.py", line 60, in _get_production_location
    raise UserError(_("Can't find any production location."))
odoo.exceptions.UserError: Can't find any production location.
```

References:
- repair production location check:
  https://github.com/odoo/odoo/blob/ab3c2d52bcaee516eae319ccd20088eb48c819f1/addons/repair/models/stock_warehouse.py#L67
- Related change:
  https://github.com/odoo/odoo/pull/168348/files#diff-3372af68f52363fdf92cc31753785c97786a58d6412046fbcab22137f2b1a274R57-R61
- mrp reference logic:
  https://github.com/odoo/odoo/blob/ab3c2d52bcaee516eae319ccd20088eb48c819f1/addons/mrp/models/stock_warehouse.py#L278-L283
- Upgrade migration reference:
  https://github.com/odoo/upgrade/blob/b46cf7ea8770c5d428ea3d569148eb76d16903b9/migrations/stock/saas~17.3.1.1/end-migrate.py#L16

OPW: 5876547
UPG: 3856191