[ADD] pos, pos_product_expiry: handle lot expiration date in POS
Steps to Reproduce:
- Install POS (with demo data).
- Activate "Lots & Serial Numbers".
- Open Furniture Shop > Select "Drawer".

Error:
`AttributeError - 'stock.lot' object has no attribute 'expiration_date'`

Cause:
The POS module directly accesses `expiration_date` on `stock.lot`,
but this field is defined in the `product_expiry` module.

Fix:
This commit adds a bridge module between `point_of_sale` and `product_expiry`.
And update the result, only when the expiry feature is enabled.

sentry-7203789966