[FIX] product, pos_restaurant: prevent error on loading demo data
Currently, an error occurs because the user deleted the 'Extras' attribute and
then tried to load the sample data, which still references it.

Steps to reproduce:
- Install 'stock' (with demo data)
- Configuration > Attributes > delete 'Extras'
- Now install 'pos_restaurant'
- Open 'Restaurant' and click on 'Load Sample' in pos config

Traceback:
ValueError: External ID not found in the system: product.pa_extras_pizza

ParseError: while parsing /home/odoo/src/odoo/saas-18.4/addons/pos_restaurant/data/scenarios/restaurant_demo_data.xml:136, somewhere inside
<record model="product.template.attribute.line" id="product_attribute_line_pizza_extra">
            <field name="product_tmpl_id" ref="pos_restaurant.product_pizza_margherita_template"/>
            <field name="attribute_id" ref="product.pa_extras_pizza"/>
            <field name="value_ids" eval="[Command.set([                     ref('product.pav_extras_pizza_pepperoni'),

We are encountering this error because the 'Extras' record is created in the
'Product' module, and the 'Stock' module includes 'Product' as a dependency.
As a result, the record becomes visible during installation and can be deleted
by the user.

This commit resolves the above error by moving the 'Extras' record to the
'pos_restaurant' module, where it is originally used. This ensures it cannot
be deleted, as its linked product will still exist.

sentry-6670301446