[FIX] website_event: prevent error when sending sign request
Currently, sending a sign request for event attendees in any language
other than English raises a client-side error.

Steps to Reproduce:
1) Install the website_event and sign modules with demo data.
2) From Settings > Translations > Languages, activate the FR language.
3) Navigate to Events, open any event form view, click the Attendees
   smart button, and open any participant form view.
4) In the chatter, click Activity, select Signature, and save.
5) Click on the profile picture and change the user language to FR.
6) Click `Demande de signature`, select any template, choose the same
   participant as the signer, and click the `Envoyer` (Save) button.

Ref Video: https://drive.google.com/file/d/1nxUk9Djcxwa1ljt_qusGnyw9rz36mZRL/view?usp=sharing

Error:
```
EvalError: Can not evaluate python expression: ([('visitor_id', 'in', [active_id])])
Error: Name 'active_id' is not defined
```

Root Cause:
since [this commit](https://github.com/odoo/enterprise/pull/93717/changes/c25288b2ec8f5370a08c1800aafc82bf8a24da67),
`next_action` was introduce in the sign request which is returning
`request.get_close_values()`. the web client now executes an action
whose domain contains `active_id` directly inside a string expression.
When this action is processed on the client side, the domain
is evaluated using the Python expression evaluator at [1].
When this domain is evaluated, 'active_id' was not present in the
evaluation context, which caused the expression evaluation failed and
raised an Error.

[1]: https://github.com/odoo/odoo/blob/3a0a0d2b47d4c060ab1b1d84320184d4adf56a2b/addons/web/static/src/core/py_js/py.js#L33-L45

Fix:
Update the domain to read the active record id from the context using
context.get('active_id'). This allows a safe evaluation of the
domain even when the active id is not present, preventing client-side
evaluation errors.

opw-5494887