[FIX] l10n_th: Invoice and credit note distribution should each contain exactly one line for the base.
```error
odoo.exceptions.ValidationError: Invoice and credit note distribution should each contain exactly one line for the base.
```

not sure if it's because of my generation or ur .xlsx