[FIX] hr(_*): use employee's calendar when processing accruals
*: holidays, contract

Steps to reproduce:
1. create an accrual plan based on worked time
2. create an accrual rule, with the source being calendar
3. create an employee that does not have a working schedule
4. create an accrual allocation for the employee with the plan
5. upon changing the date of the allocation, an error message pops
up

Error:
```
  File "/data/build/odoo/addons/resource/models/resource_mixin.py", line 149, in _get_leave_days_data_batch
    attendances = calendar._attendance_intervals_batch(from_datetime, to_datetime, calendar_resources)
  File "/data/build/odoo/addons/resource/models/resource_calendar.py", line 278, in _attendance_intervals_batch
    self.ensure_one()
  File "/data/build/odoo/odoo/models.py", line 5867, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: resource.calendar()
```

This commit raises a readable error to make sure the employee
has a valid working schedule when processing accrual plans
based on worked time.

task-4100439