[FIX] web: Prevent race condition when adding properties
This error occurs when a model has properties and a computed field or onchange method depends on them.

record.update() is asynchronous. When an onchange or computed field is triggered, an additional request is sent to the server, increasing the time required to complete the update. See:

https://github.com/odoo/odoo/blob/727fe7412bb37c1664106625e248264d2aab6809/addons/web/static/src/model/relational_model/record.js#L1207-L1211

However, PropertiesField is rendered before the update is completed. See:

https://github.com/odoo/odoo/blob/727fe7412bb37c1664106625e248264d2aab6809/addons/web/static/src/views/fields/properties/properties_field.js#L86

As a result, the property labels are not yet available and the following traceback is raised:

TypeError: Cannot read properties of undefined (reading 'getRootNode')

After this commit, the update is awaited before rendering PropertiesField, ensuring that the property labels are available.

Steps to reproduce:

Install the example module.
Open or create a project task.
From the Action menu, click "Add Properties".

The error is raised.