[FIX] base: prevent error on running custom user action
Error occurs when running a user made server action. Because action variable has
`incorrect datatype`, we will use list for replication.

**Steps to reproduce:**
* Install `sale_management` module.
* `Settings>Technical>Actions>Server Actions > New`
* Set `Type: Execute code` and `Model: Sales Order`
* Inside code enter the following `action = [{'binding_model_id': False,
'binding_type': 'action', 'binding_view_types': 'list,form'}]`
* Create `contextual action > Sales > Select SO > Actions > Your created action`

`AttributeError: 'list' object has no attribute 'setdefault'`

**Solution:**
* Ensure a `ValidationError` is raised if a server action assigns a
  non-dictionary value to action, whether at the time of saving the code or
  during runtime execution.

Sentry-5862504065