[FIX] stock:  Prevent error in Product Routes Report if Source Location is empty
This error occurs when users view the Product Routes Report.
Steps to Reproduce:
 - Install the stock and mrp modules.
 - In stock, open Products.
 - In the Inventory tab, enable Manufacture in Routes.
 - Clear the Production Location field.
 - Click View Diagram in Routes.

ValueError: False is not in list

This error occurs because, in Warehouse > Routes, when a rule is created with
the Manufacture action, the Source Location field is not required. However,
when generating the Product Routes Report, the system attempts to access
this field even if it is empty, resulting in an error.

This commit ensures the Product Routes Report view correctly

Sentry-5682671428